### ISSUE TITLE
一点小疑惑

### ISSUE THREAD

**Issue by DWorld15** [wb04307201/message-spring-boot-starter#1]
已经成功使用本项目发送钉钉消息了，但是使用起来有一点问题。
        <dependency>
            <groupId>com.gitee.wb04307201</groupId>
            <artifactId>message-spring-boot-starter</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-parent</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
这个starter下面既有log4j，又有logback依赖，会导致应用无法启动，slf4j报错，我只有排除了logback才能正常启动
请问这个为何要这样设计

**Comment by wb04307201** [comment]
因为之前那个版本粗心没进行测试，没发现这个问题
log4j是钉钉的SDK里面带的，有依赖缺陷，为了修复这个缺陷升级了log4j，又顺手添加了log4j-slf4j-impl，这个依赖导致了和logback的冲突
gihub这边不经常看，回复不太及时，有问题可以到gitee上面提，那边每天都会翻翻
https://gitee.com/wb04307201/message-spring-boot-starter
